namespace WindowThing.Bindings.Glfw;

public enum GlfwWindowHint
{
	Resizable = Glfw.Resizable,
	Visible = Glfw.Visible,
	Decorated = Glfw.Decorated,
	Focused = Glfw.Focused,
	AutoIconify = Glfw.AutoIconify,
	Floating = Glfw.Floating,
	Maximized = Glfw.Maximized,
	CenterCursor = Glfw.CenterCursor,
	TransparentFramebuffer = Glfw.TransparentFramebuffer,
	FocusOnShow = Glfw.FocusOnShow,
	ScaleToMonitor = Glfw.ScaleToMonitor,
	RedBits = Glfw.RedBits,
	GreenBits = Glfw.GreenBits,
	BlueBits = Glfw.BlueBits,
	AlphaBits = Glfw.AlphaBits,
	DepthBits = Glfw.DepthBits,
	StencilBits = Glfw.StencilBits,
	AccumRedBits = Glfw.AccumRedBits,
	AccumGreenBits = Glfw.AccumGreenBits,
	AccumBlueBits = Glfw.AccumBlueBits,
	AccumAlphaBits = Glfw.AccumAlphaBits,
	AuxBuffers = Glfw.AuxBuffers,
	Samples = Glfw.Samples,
	RefreshRate = Glfw.RefreshRate,
	Stereo = Glfw.Stereo,
	SrgbCapable = Glfw.SrgbCapable,
	DoubleBuffer = Glfw.Doublebuffer,
	ClientApi = Glfw.ClientApi,
	ContextCreationApi = Glfw.ContextCreationApi,
	ContextVersionMajor = Glfw.ContextVersionMajor,
	ContextVersionMinor = Glfw.ContextVersionMinor,
	ContextRobustness = Glfw.ContextRobustness,
	ContextReleaseBehaviour = Glfw.ContextReleaseBehavior,
	OpenglForwardCompat = Glfw.OpenglForwardCompat,
	OpenglDebugContext = Glfw.OpenglDebugContext,
	OpenglProfile = Glfw.OpenglProfile,
	CocoaRetinaFramebuffer = Glfw.CocoaRetinaFramebuffer,
	CocoaFrameName = Glfw.CocoaFrameName,
	CocoaGraphicsSwitching = Glfw.CocoaGraphicsSwitching,
	X11ClassName = Glfw.X11ClassName,
	X11InstanceName = Glfw.X11InstanceName
}
