namespace RenderThing.Bindings.Glfw;

public enum GlfwWindowHint
{
	Resizable = Glfw.RESIZABLE,
	Visible = Glfw.VISIBLE,
	Decorated = Glfw.DECORATED,
	Focused = Glfw.FOCUSED,
	AutoIconify = Glfw.AUTO_ICONIFY,
	Floating = Glfw.FLOATING,
	Maximized = Glfw.MAXIMIZED,
	CenterCursor = Glfw.CENTER_CURSOR,
	TransparentFramebuffer = Glfw.TRANSPARENT_FRAMEBUFFER,
	FocusOnShow = Glfw.FOCUS_ON_SHOW,
	ScaleToMonitor = Glfw.SCALE_TO_MONITOR,
	RedBits = Glfw.RED_BITS,
	GreenBits = Glfw.GREEN_BITS,
	BlueBits = Glfw.BLUE_BITS,
	AlphaBits = Glfw.ALPHA_BITS,
	DepthBits = Glfw.DEPTH_BITS,
	StencilBits = Glfw.STENCIL_BITS,
	AccumRedBits = Glfw.ACCUM_RED_BITS,
	AccumGreenBits = Glfw.ACCUM_GREEN_BITS,
	AccumBlueBits = Glfw.ACCUM_BLUE_BITS,
	AccumAlphaBits = Glfw.ACCUM_ALPHA_BITS,
	AuxBuffers = Glfw.AUX_BUFFERS,
	Samples = Glfw.SAMPLES,
	RefreshRate = Glfw.REFRESH_RATE,
	Stereo = Glfw.STEREO,
	SrgbCapable = Glfw.SRGB_CAPABLE,
	DoubleBuffer = Glfw.DOUBLEBUFFER,
	ClientApi = Glfw.CLIENT_API,
	ContextCreationApi = Glfw.CONTEXT_CREATION_API,
	ContextVersionMajor = Glfw.CONTEXT_VERSION_MAJOR,
	ContextVersionMinor = Glfw.CONTEXT_VERSION_MINOR,
	ContextRobustness = Glfw.CONTEXT_ROBUSTNESS,
	ContextReleaseBehaviour = Glfw.CONTEXT_RELEASE_BEHAVIOR,
	OpenglForwardCompat = Glfw.OPENGL_FORWARD_COMPAT,
	OpenglDebugContext = Glfw.OPENGL_DEBUG_CONTEXT,
	OpenglProfile = Glfw.OPENGL_PROFILE,
	CocoaRetinaFramebuffer = Glfw.COCOA_RETINA_FRAMEBUFFER,
	CocoaFrameName = Glfw.COCOA_FRAME_NAME,
	CocoaGraphicsSwitching = Glfw.COCOA_GRAPHICS_SWITCHING,
	X11ClassName = Glfw.X11_CLASS_NAME,
	X11InstanceName = Glfw.X11_INSTANCE_NAME
}
